# Page settings

baseurl = "//kmarchant.com"
languageCode = "en-au"
title = "Keith Marchant CV"
theme = "orbit"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "CV based on Hugo Responsive Resume Theme"
    author = "Keith Marchant"
    title = "Keith Marchant CV"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Keith Marchant"
        tagline = "Development Manager"
        avatar = "profile.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/keith-marchant-906747b"
        title = "Keith-Marchant"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/keith-marchant"
        title = "Keith-Marchant"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//kmarchant.com"
        title = "KMarchant.com"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Bachelor of Computer Science with Honours"
        college = "University of Waterloo"
        dates = "2005 - 2010"

    # Languages section
    [params.language]
        enable = false
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Soccer"

        [[params.interests.list]]
        interest = "Running"

        [[params.interests.list]]
        interest = "Cycling"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Development manager with 10 years’ experience developing web and server applications for multiple industries. Currently focused on growing a core team of developers while delivering a transition from monolithic C# applications to cloud managed microservices. Seeking opportunities to gain experience using cloud-based solutions and applying my knowledge to further your business needs."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Development Manager"
        dates = "May 2016 - Present"
        company = "InfoTrack Pty Ltd, Sydney"
        summary = "InfoTrack is a market leader in providing search and workflow services to the legal industry. InfoTrack provides a single platform for E-Conveyancing, due diligence, and more; tightly integrated into multiple practice management software solutions."
        details = [
            "Implemented the vision of a shared software platform across three countries",
            "Transitioned from a monolithic code base to multiple microservices running in containerised environments",
            "Managed the development of the core platform and infrastructure used to generate more than $1.5 million/week",
            "Managed and mentored multiple developers",
            "Migrated hosting from private cloud to AWS and assisted with the adoption of AWS managed services",
            "Managed the replacement of synchronous systems with an event driven architecture backed by MassTransit and AmazonMQ"
        ]

        [[params.jobs.list]]
        position = ".Net Developer"
        dates = "Sep 2015 - Apr 2016"
        company = "InfoTrack Pty Ltd, Sydney"
        summary = ""
        details = [
            "Released new corporate product offerings integrated with ASIC written with Knockout JS and .NET MVC",
            "Implemented MongoDB document storage for existing XML archives",
            "Implemented new CI/CD processes and infrastructure worldwide using TeamCity and Octopus Deploy"
        ]

        [[params.jobs.list]]
        position = "Senior Software Developer"
        dates = "May 2010 - Aug 2015"
        company = "BlueSun Inc, Ontario, Canada"
        summary = "BlueSun is a small Canadian company that specialises in providing web software for the life insurance and mutual fund industries via their WealthServ products."
        details = [
            "Developed new products using C#, Java, JavaScript, MVC, & SQL Server",
            "Managed the WealthServ Insurance product as the lead developer",
            "Triaged all issues related to the WealthServ Insurance platform",
            "Converted client data for new client installations",
            "Led the product support team",
            "Supported the sales process for prospective clients"
        ]

        [[params.jobs.list]]
        position = "Associate Software Engineer"
        dates = "May 2009 - Aug 2009"
        company = "Electronic Arts Canada"
        summary = "EA Canada is responsible for the development of multiple major sports video game franchises released yearly."
        details = [
            "Employed as part of a work placement through the University of Waterloo",
            "Assisted in the development of FIFA 10 on Xbox 360 & PS3",
            "Implemented tool support code in C# and C++/CLI",
            "Developed runtime code in C++ for character animations"
        ]

        [[params.jobs.list]]
        position = "Programming Intern"
        dates = "May 2008 - Dec 2008"
        company = "Atlantis Cyberspace Inc., Hawaii"
        summary = "Atlantis Cyberspace is a small American company based in Hawaii that develops training software for the US armed forces."
        details = [
            "Developed database interface layer for Unreal 3 based simulation software",
            "Produced a web portal using ASP.NET web forms for commanding officers to receive real-time reports of simulation participants",
            "Implemented remoting methods for a server/client architecture",
            "Implemented C++/CLI and C# interfaces for game engine access"
        ]

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "Side projects and learning exercises"

        [[params.projects.list]]
        title = "Document Manager"
        url = "https://github.com/keith-marchant/document-manager"
        tagline = "API to create, upload, and convert documents to various formats"

        [[params.projects.list]]
        title = "CV"
        url = "https://github.com/keith-marchant/kmarchant-hugo"
        tagline = "The Hugo project powering this site"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "C#"
        level = "90%"
                
        [[params.skills.list]]
        skill = "SQL"
        level = "80%"

        [[params.skills.list]]
        skill = "WCF"
        level = "80%"

        [[params.skills.list]]
        skill = "gRPC"
        level = "70%"

        [[params.skills.list]]
        skill = "F#"
        level = "60%"

        [[params.skills.list]]
        skill = "JavaScript"
        level = "60%"

        [[params.skills.list]]
        skill = "TeamCity & Octopus Deploy"
        level = "90%"

        [[params.skills.list]]
        skill = "Git"
        level = "90%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Keith Marchant"
