name: cv_build
on: [push]
jobs:
    build_deploy:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@master
        - name: up
          env:
            SOURCE_DIR: './public'
            AWS_REGION: 'ap-southeast-2'
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          run: |
            sudo apt-get install hugo
            hugo
            aws s3 sync ${SOURCE_DIR} s3://${AWS_S3_BUCKET} \
              --acl public-read \
              --region ${AWS_REGION} \
              --no-progress